---
- name: Deploy Docker Container
  hosts: all
  tasks:
    - name: Pull Docker Image from Docker Hub 
      docker_image:
              name: adityagowda2000/spe-mini-project
              source: pull
